version: '3'
services:
    nginx:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ./src:/application
            - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        networks:
            - www

    php-fpm:
        image: php:fpm-alpine
        volumes:
            - ./src:/application
        networks:
            - www

networks:
    www:
